artyParty/urls.py
from artyParty import views
from django.conf.urls import url
from django.urls import path
from django.views.generic import TemplateView

app_name = 'arty'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('about/', views.about, name='about'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('my_account/', views.my_account, name='my_account'),
    path('my_account/edit_details/', views.edit_details, name='edit_details'),
    path('galleries/', views.galleries, name='galleries'),
    path('galleries/<slug:gallery_name_slug>/', views.show_gallery, name='show_gallery'),
    path('galleries/<slug:gallery_name_slug>/<slug:piece_name_slug>/', views.piece, name='piece'),
    path('galleries/<slug:gallery_name_slug>/<slug:piece_name_slug>/add_review', views.add_review, name='add_review'),
]

wad_2_team_project/urls.py
from django.contrib import admin
from django.urls import path, include
from artyParty import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name='home'),
    path('arty/', include('artyParty.urls')),
    # check how folders are working on thursday"""
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
    path('', views.home, name='home'),
    path('login/', views.user_login, name='login'),
    path('sign_up/', views.user_sign_up, name='sign_up'),
    path('about/', views.about, name = 'about'),
    path('contact_us/', views.contact_us, name = 'contact_us'),
    path('my_account/', views.my_account, name = 'my_account'),
    path('my_account/add_piece', views.add_piece, name = 'add_piece'),
    path('my_account/add_gallery', views.add_gallery, name = 'add_gallery'),
    path('my_account/manage_users', views.manage_users, name = 'manage_users'),
    path('my_account/edit_details', views.edit_details, name = 'edit_details'),
    path('my_account/posts', views.posts, name = 'posts'),
    path('category/', views.category, name='category'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/<slug:gallery_name_slug>/', views.show_gallery, name='show_gallery'),
    path('gallery/<slug:gallery_name_slug>/<slug:piece_name_slug>/', views.show_piece, name='show_piece'),
    path('gallery/<slug:gallery_name_slug>/<slug:piece_name_slug>/<slug:review_name_slug>/', views.show_review, name='show_review'),
    
    # think this is in twice
    #path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),


    saved for artyParty views.py


"""

artyParty/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class UserProfile(models.Model):
    USER_TYPE_MAX_LENGTH = 5

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    userID = models.IntegerField(unique=True, blank=False)

    def __str__(self):
        return self.user.username


class Gallery(models.Model):
    GALLERY_NAME_MAX_LENGTH = 50

    gallery_name = models.CharField(max_length=GALLERY_NAME_MAX_LENGTH, blank=False)
    gallery_id = models.IntegerField(unique=True, blank=False)
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    gallery_img = models.ImageField(blank=False, upload_to='artyParty_images')
    gallery_description = models.TextField(blank=True)
    slug = models.SlugField(blank=True, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.gallery_name)
        super(Gallery, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Galleries'

    def __str__(self):
        return str(self.gallery_id)


class Piece(models.Model):
    PIECE_NAME_MAX_LENGTH = 50
    PIECE_CATEGORY_MAX_LENGTH = 20
    MAX_AUTHOR_LENGTH = 20

    gallery_id = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    piece_img = models.ImageField(blank=False, upload_to='artyParty_images')
    piece_id = models.IntegerField(unique=True, blank=False)
    piece_name = models.CharField(max_length=PIECE_NAME_MAX_LENGTH, blank=False)
    author = models.CharField(max_length=MAX_AUTHOR_LENGTH, blank=False)
    period = models.CharField(max_length=PIECE_CATEGORY_MAX_LENGTH, blank=False)
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.piece_name)
        super(Piece, self).save(*args, **kwargs)

    def __str__(self):
        return (str(self.piece_name))


class Review(models.Model):
    review_id = models.IntegerField(unique=True, )
    piece_id = models.ForeignKey(Piece, on_delete=models.CASCADE, blank=False)
    rating = models.IntegerField(blank=False)
    userID = models.ForeignKey(User, on_delete=models.CASCADE, )
    review = models.TextField()

    def __str__(self):
        return self.review[:10]

artyParty/forms.py
from artyParty.models import UserProfile, Review
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ()


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email',)


class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('rating', 'review',)

artyParty/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from artyParty.forms import UserForm, UserProfileForm, EditUserForm, AddReviewForm
import requests
from artyParty.models import Piece, Gallery, Review, UserProfile
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.http import JsonResponse


# maybe rename this or homepage to have the same name?
def home(request):
    # top 4 pieces ordered by popularity
    # change template to display them line 11

    # need to change carosel to images from galleries
    # need to figure out how to sort by rating
    piece_list = Piece.objects.order_by('-piece_id')[:4]
    galleries = Gallery.objects.all()

    context_dict = {}

    context_dict['pieces'] = piece_list
    context_dict['gallery'] = galleries

    return render(request, 'artyParty/homepage.html', context=context_dict)


def user_login(request):
    # can we copy from rango?

    ############################################################################
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('arty:home'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your artyParty account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'artyParty/login.html')
    ############################################################################


@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('arty:home'))


def sign_up(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.

            profile = profile_form.save(commit=False)
            profile.user = user

            max = 0
            for profiles in UserProfile.objects.all():
                if profiles.userID > max:
                    max = profiles.userID

            profile.userID = max + 1


            # Now we save the UserProfile model instance.
            profile.save()



            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request, 'artyParty/sign_up.html',
                    context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})
    ############################################################################


def about(request):
    context_dict = {}
    # no real need for context come back to
    #

    return render(request, 'artyParty/about.html', context=context_dict)


def contact_us(request):
    # what happens to submitted form? -> maybe put into db?
    # redirect to homepage
    context_dict = {}

    return render(request, 'artyParty/contact_us.html', context=context_dict)


@login_required
def my_account(request):
    # @loginrequired decorator

    form = EditUserForm(instance = request.user)


    context_dict = {

    }

    # context_dict[''] =

    return render(request, 'artyParty/myaccount.html', context=context_dict)


@login_required
def add_piece(request):
    # take from rango
    context_dict = {}

    return render(request, 'artyParty/add_pieces.html', context=context_dict)


@login_required
def add_gallery(request):

    context_dict = {}

    return render(request, 'artyParty/add_galleries.html', context=context_dict)


@login_required
def manage_users(request):

    context_dict = {}

    return render(request, 'artyParty/manage_users.html', context=context_dict)


@login_required
def edit_details(request):

    message = ""
    if request.method == 'POST':

        user_form = EditUserForm(request.POST, instance = request.user)

        if user_form.is_valid():

            user_form.save()
            message = "Details updated"

        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors)

    form = EditUserForm(instance = request.user)

    context_dict = {
        "form":form,
        "message":message,
    }


    return render(request, 'artyParty/edit_details.html', context=context_dict)


def posts(request):
    # what is this posts page about? Is this where we post info?

    context_dict = {}

    return render(request, 'artyParty/post.html', context=context_dict)

    # res = requests.get("https://en.wikipedia.org/api/rest_v1/page/summary/Christ_of_Saint_John_of_the_Cross")
    # data = res.json()
    # context_dict = {'descript': data['extract']}
    # return render(request, "View Posts", context_dict)


def galleries(request):
    ## see rango show_category

    gallery_list = Gallery.objects.order_by("gallery_id")  # this 3 needs to be the length of gallery

    context_dict = {'galleries': gallery_list}
    return render(request, 'artyParty/get_gallery_list.html', context=context_dict)


def show_gallery(request, gallery_name_slug):
    # see rango show_category
    # querey db for all pieces where gallery == passed val
    context_dict = {}
    try:
        gallery = Gallery.objects.get(slug=gallery_name_slug)
        pieces = Piece.objects.filter(gallery_id=gallery)
        context_dict['pieces'] = pieces
        context_dict['gallery'] = gallery
        ctx = {}
        for p in pieces:
            link = "https://en.wikipedia.org/api/rest_v1/page/summary/{}".format(p.slug.replace("-", "_"))
            res = requests.get(link)
            data = res.json()
            extract = data['extract']
            ctx[p.slug] = extract
        context_dict['ctx'] = ctx

    except Gallery.DoesNotExist:
        context_dict['pieces'] = None
        context_dict['gallery'] = None

    return render(request, 'artyParty/gallery.html', context=context_dict)


def piece(request, gallery_name_slug, piece_name_slug):

    context_dict = {}
    try:
        p = Piece.objects.get(slug=piece_name_slug)
        gallery = Gallery.objects.get(slug=gallery_name_slug)
        context_dict['piece'] = p
        context_dict['gallery'] = gallery
        res = requests.get("https://en.wikipedia.org/api/rest_v1/page/summary/{}".format(p.slug.replace("-", "_")))
        data = res.json()
        extract = data['extract']
        context_dict['extract'] = extract
        reviews = Review.objects.filter(piece_id_id=p)
        context_dict['reviews'] = reviews
        r = {}
        for review in reviews:
            r[review.review_id] = range(review.rating)
        context_dict['range'] = r

    except Piece.DoesNotExist:
        context_dict['piece'] = None
        context_dict['gallery'] = None
    return render(request, 'artyParty/piece.html', context=context_dict)

def show_review(request):
    ## see rango show_category

    # which template is this?
    # return render(request, 'artyParty/show_review.html', context=context_dict)

templates/artyParty/add_review.html
{% extends 'artyParty/base.html' %}
{% load staticfiles %}

{% block title_block %}
Add Review
{% endblock %}

{% block extral_index_block %}
<li><a href="{% url 'arty:show_gallery' gallery.slug %}">{{ gallery.gallery_name }}</a></li>
<li><a href="{% url 'arty:piece' gallery.slug piece.slug %}">{{ piece.piece_name }}</a></li>
{% endblock %}

{% block body_block %}
<div class="container wells">
    <h1><strong>Add Review</strong></h1><br/>
    <form id="review" method="post" action="{% url 'arty:add_review' gallery.slug piece.slug %}">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Add Review">
    </form>

    <button class="btn btn-default">
        <a class="a_reset" class="btn btn-default" href="{% url 'arty:sign_up' %}">Sign Up</a>
    </button>
    <br/>
    <button class="btn btn-default">
        <a class="a_reset" href="{% url 'arty:home' %}">Back to home page</a>
    </button>
</div>
{% endblock %}

templates/artyParty/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang='en'>
    <head>
        <meta charset="UTF-8" />
        <title>
            Arty Party -
            {% block title_block %}

            {% endblock %}
        </title>
<!--{#        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>#}-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="{% static "search.js" %}"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

    </head>
    <body>
        <nav class="navbar navbar-expand-sm">
            <div class="container-fluid">
            {# <div class= top_line> #}
                    <h1 class="logo">Arty <br> Party</h1>
                    <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'arty:my_account'%}">{{user.username}}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'arty:logout' %}">Logout</a></li>
                        <!-- Show these links when the user is logged in -->
                    {% else %}
                        <!-- Show these links when the user is NOT logged in -->
                        <li class="nav-item"><a class="nav-link" href="{% url 'arty:login' %}">Login</a></li>
                    {% endif %}
                        <!-- Outside the conditional statements, ALWAYS show -->
                        <li class="nav-item"><a class="nav-link" href="{% url 'arty:about' %}">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'arty:contact_us' %}">Contact</a></li>
                    </ul>
            {# </div> #}
            </div>
        </nav>
        <ul class="index_line">
            <li><a href="{% url 'arty:home' %}">Homepage</a></li>
            <li><a href="{% url 'arty:galleries' %}">Galleries</a></li>
            {% block extral_index_block %}
            {% endblock %}
        </ul>

        <div>
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

templates/artyParty/contact_us.html
{% extends 'artyParty/base.html' %}
{% load staticfiles %}

{% block title_block %}
Contact_us
{% endblock %}

{% block body_block %}
<div class="center_text">
    <h2>WAD2 Group 2A</h2>
    We will contact you as soon as possible after you finished the contact form.
    <br/>
</div>
<div class="container wells">
    <form id="contact_form" method="POST" action="{% url 'arty:contact_us' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="text">Name:</label>
            <input type="text" class="form-control" name="username" id="text" value="" placeholder="Enter your name"/>

        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" id="email" name="email" value="" placeholder="Enter your email"/>
        </div>

        <div class="form-group">
            <label for="number"> Mobile:</label>
            <input type="number" class="form-control" id="number" name="mobile" value=""
                    placeholder="Enter your Mobile number"/>
        </div>
        <div class="form-group">
            <label for="message"> Message:</label>
            <input type="text" class="form-control" id="message" name="questions" value=""
                    placeholder="Enter your Question"/>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>
{% endblock %}

templates/artyParty/edit_details.html
{% extends 'artyParty/base.html' %}
{% load staticfiles %}

{% block title_block %}
Myaccount
{% endblock %}

{% block body_block %}
{% if user.is_authenticated %}

<div>
    {{message}}
</div>
<div class="container wells">
    <h1><strong>Edit Details</strong></h1><br/>
    <form id="personal_detail" method="post" action="{% url 'arty:edit_details' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <!--            <div class ="form-group">-->
        <!--                <input type="hidden" name="csrfmiddlewaretoken" value="ovzVsYQBIlgWs8r137TTMOGzy3aIVTcpTRAW5m8YfFdScEDh5buk28yhBs2smtGX">-->
        <!--                <p>-->
        <!--                    <label for="id_username">Username:</label>-->
        <!--                    <input type="text" name="username" class="form-control" value="scott" maxlength="150" required id="id_username"> <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>-->
        <!--                </p>-->
        <!--            </div>-->
        <!--            <div class ="form-group">-->
        <!--                <p>-->
        <!--                    <label for="id_email">Email address:</label>-->
        <!--                    <input type="email" name="email" class="form-control" value="s@p.com" maxlength="254" id="id_email">-->
        <!--                </p>-->
        <!--            </div>-->
        <input type="submit" value="Edit Details">
    </form>
</div>


{% else %}
Please login to access details.
<br>
Click <a href="{% url 'arty:login' %}">here</a> to login.
{% endif %}
{% endblock %}

templates/artyParty/gallery.html
{% extends "artyParty/base.html" %}
{% load staticfiles %}

{% block title_block %}
{% if gallery %}{{ gallery.gallery_name }}{% else %}
Unknown Gallery
{% endif %}
{% endblock %}

<!--proof of concept for breadcrumb trail-->
{% block extral_index_block %}
<li><a href="{% url 'arty:show_gallery' gallery.slug %}">Pieces in {{ gallery.gallery_name }}</a></li>
{% endblock %}

{% block body_block %}
<div class="container">
    <div class="search_bar">
        <h2>{{ gallery.gallery_name }}</h2>

        <div class="col-6 align-left">
            <form class="form-inline" role="search">
                <i id="search-icon" class="fas fa-search" aria-hidden="true"></i>
                <input type="text" class="form-control form-control-sm ml-3 w-75" name="q" id="user-input"
                        placeholder="Search..." aria-label="Search for pieces">
            </form>
        </div>
    </div>

    <div class="container-fluid">
        {% if gallery %}
        {% if pieces %}
        <table class="table wells">
            <thead class="opacity1">
            <tr>
                <th class="col-sm-5">Art Piece Image</th>
                <th class="col-sm-3">Art Piece Name</th>
                <th class="col-sm-4">Art Piece description</th>
            </tr>
            </thead>
            <tbody class="opacity1" id="myTable">
            <div id="replaceable-content">
                {% include 'artyParty/pieces_results_partial.html' %}
            </div>
            </tbody>
        </table>
        {% else %}
        <strong>There are no pieces present.</strong>
        {% endif %}
        {% else %}
        <strong>There are no galleries present.</strong>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/artyParty/login.html
{% extends 'artyParty/base.html' %}
{% load staticfiles %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}
<div class="container wells">
    <h1><strong>Login</strong></h1><br/>
    <form id="login_form" method="post" action="{% url 'arty:login' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="text">Username:</label>
            <input type="text" class="form-control" name="username" value="" size="50"/>
        </div>
        <div class="form-group">
            <label for="text">Email:</label>
            <input type="email" class="form-control" name="email" value="" size="50"/>
        </div>
        <div class="form-group">
            <label for="text">Password:</label>
            <input type="password" class="form-control" name="password" value="" size="50"/>
        </div>
        <input type="submit" class="btn btn-default" value="submit"/>
        <button class="btn btn-default">
            <a class="a_reset" class="btn btn-default" href="{% url 'arty:sign_up' %}">Sign Up</a>
        </button>
        <br/>
        <button class="btn btn-default">
            <a class="a_reset" href="{% url 'arty:home' %}">Back to home page</a>
        </button>
    </form>
</div>
{% endblock %}  

templates/artyParty/myaccount.html
{% extends 'artyParty/base.html' %}
{% load staticfiles %}

{% block title_block %}
Myaccount
{% endblock %}

{% block body_block %}
{% if user.is_authenticated %}

<div>
    <p class="info p">
        Username = {{user.username}}
    </p>
    <br/>
    <p class="info p">
        Email = {{user.email}}
    </p>
</div>
<br/>
<button>
    <a class="a_reset" href="{% url 'arty:edit_details' %}">Edit Details</a>
</button>


{% if user.is_power_user %}
<button><a href="{% url 'arty:add_piece' %}">add pieces</a></button>
<button><a href="{% url 'arty:posts' %}">view posts</a></button>
{% if user.is_owner %}
<button><a href="{% url 'arty:add_gallery' %}">add gallery</a></button>
<button><a href="{% url 'arty:manage_users' %}">manage users</a></button>
{% endif %}
{% endif %}
{% else %}
Please login to access details.
<br>
Click <a href="{% url 'arty:login' %}">here</a> to login.
{% endif %}
{% endblock %}

templates/artyParty/piece.html
{% extends 'artyParty/base.html' %}
{% load staticfiles %}

{% block title_block %}
{% if piece %}{{ piece.piece_name }}{% else %}
Unknown Piece
{% endif %}
{% endblock %}

{% block extral_index_block %}
<li><a href="{% url 'arty:show_gallery' gallery.slug %}">{{ gallery.gallery_name }}</a></li>
<li><a href="{% url 'arty:piece' gallery.slug piece.slug %}">{{ piece.piece_name }}</a></li>
{% endblock %}

{% block body_block %}
<div class="container">
    {% if piece %}
    <h1>{{ piece.piece_name }}</h1>
    <hr>
    <div class="row">
        <div class="col-sm-5 list-group">
            <ul class="">
                <li class="list-group-item ">Name: <span class="badge">{{ piece.piece_name }}</span></li>
                <li class="list-group-item">Author: <span class="badge">{{ piece.author }}</span></li>
                <li class="list-group-item">Period: <span class="badge">{{ piece.period }}</span></li>
            </ul>

            <div class="wells">
                <p>{{ extract }}</p>
            </div>
        </div>
        <div class="col-sm-7">
            <img src="{{piece.piece_img.url}}" alt="piece image" class="img-responsive">
        </div>
    </div>
    <br>
    <div class="wells">
        <div class="row">
            <h4 class="col-sm-10">Comments</h4>
            {% if user.is_authenticated %}
            <a class="col-sm-2 text-dark" href="{% url 'arty:add_review' gallery.slug piece.slug %}">Add Review</a>
            {% endif %}
        </div>
        {% if reviews %}
        <div class="less_wide">
            {% for review in reviews %}
            <div class="wells less_wide row">
                <div class="badge col-sm-5">
                    <span class="big ">{{ review.rating }}</span>
                    <div class="inline-block starcont">
                        <p class="stars">
                            {% for key,value in range.items %}
                            {% if key == review.review_id %}
                            {% for i in value %}
                            ★
                            {% endfor %}
                            {% endif %}
                            {% endfor %}
                        </p>
                    </div>
                </div>
                <p class="col-sm-7">{{ review.review }}</p>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    {% else %}
    The specified piece does not exist.
    {% endif %}
</div>
{% endblock %}

templates/artyParty/pieces_results_partial.html
{# pieces_results_partial.html #}
{% load staticfiles %}
{% if pieces %}
<ul>
    {% for p in pieces %}
    <tr>
        <td>
            <img src="{{p.piece_img.url}}" class="img-responsive" alt="img">
        </td>
        <td>
            <a href="{% url 'arty:piece' gallery_name_slug=gallery.slug piece_name_slug=p.slug %}">{{p.piece_name}}</a>
        </td>
        <td>
            {% for key,value in ctx.items %}
            {% if key == p.slug %}
            <p> {{ value }}</p>
            {% endif %}
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
</ul>
{% else %}
<p>No artists found.</p>
{% endif %}